dist: trusty
language: ruby
sudo: false

rvm:
  - 2.4.1

env:
  - TRAVIS_NODE_VERSION="7"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/jekyll/vendor
    - $TRAVIS_BUILD_DIR/node_modules

before_script:
  - cd $TRAVIS_BUILD_DIR/jekyll && bundle install
  - cd $TRAVIS_BUILD_DIR && npm install

script:
  - npm run webpack:prod
  - cd $TRAVIS_BUILD_DIR/jekyll && bundle exec rake test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

deploy:
  provider: pages
  local-dir: jekyll/_site
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  verbose: true
  on: # Only deploy changes committed to develop branch
    branch: develop
