name:        Adventurous Web Design
markdown:    kramdown
highlighter: rouge

collections:
  work:
    output:    true
    permalink: /:collection/:slug

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
