name:        Adventurous Web Design
markdown:    kramdown
highlighter: rouge

url:       "https://adventurouswebdesign.com"
permalink: /blog/:title:output_ext

collections:
  work:
    output:    true
    permalink: /:collection/:slug.html

defaults:
  -
    scope:
      path: ''
      type: 'work'
    values:
      image_caption_container_close: '</div></div>'
      image_caption_container_open: '<div class="portfolio-container"><div class="portfolio__body">'
      image_gallery_container_close: '</div></div>'
      image_gallery_container_open: '<div class="portfolio-container"><div class="portfolio__body">'
      fullwidth_container_close: '</div></div>'
      fullwidth_container_open: '<div class="portfolio-container"><div class="portfolio__body">'
      layout: 'work'

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - docker-compose.yml
  - _src
  - _images
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - Session.vim
  - webpack.config.js
  - config
  - icon.png
