name:        Adventurous Web Design
markdown:    kramdown
highlighter: rouge

collections:
  work:
    output:    true
    permalink: /:collection/:slug.html

defaults:
  -
    scope:
      path: ''
      type: 'work'
    values:
      image_caption_container_close: '</div></div>'
      image_caption_container_open: '<div class="portfolio-container"><div class="portfolio__body">'
      image_gallery_container_close: '</div></div>'
      image_gallery_container_open: '<div class="portfolio-container"><div class="portfolio__body">'
      fullwidth_container_close: '</div></div>'
      fullwidth_container_open: '<div class="portfolio-container"><div class="portfolio__body">'
      layout: 'work'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - Session.vim
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
